# Use postgres/example user/password credentials
version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: drupal
      POSTGRES_DB: drupal
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-h',
          'localhost',
          '-p',
          '5432',
          '-d',
          'dbdocker',
          '-U',
          'userdocker',
        ]
      timeout: 3s
      retries: 10
      start_period: 20s

  drupal:
    image: drupal
    ports:
      - '8080:80'
    depends_on:
      - postgres
