# Use postgres/example user/password credentials
version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: drupal
      POSTGRES_DB: drupal
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432

  drupal:
    image: drupal
    ports:
      - '8080:80'
    depends_on:
      - postgres
